anaconda: Update to 23.19.10
Use the output of

  git diff --full-index --binary anaconda-22.20.13-1..anaconda-23.19.10-1

from anaconda's git repository and fix-up merge conflicts.

diff --git a/anaconda/dracut/anaconda-diskroot b/anaconda/dracut/anaconda-diskroot
--- a/anaconda/dracut/anaconda-diskroot
+++ b/anaconda/dracut/anaconda-diskroot
@@ -13,15 +13,22 @@ run_checkisomd5() {
         if [ "$fs" = "iso9660" -o "$fs" = "udf" ]; then
             [ -x /bin/plymouth ] && /bin/plymouth --hide-splash
             if [ -n "$DRACUT_SYSTEMD" ]; then
-                p=$(str_replace "$livedev" "-" '\x2d')
+                p=$(dev_unit_name "$livedev")
                 systemctl start checkisomd5@${p}.service
-                status=$(systemctl -p ExecMainStatus show checkisomd5@${p}.service)
-                splitsep "=" "$status" ignore rc
+                retcode=$(systemctl -p ExecMainStatus show checkisomd5@${p}.service)
+                status=$(systemctl -p ActiveState show checkisomd5@${p}.service)
+                splitsep "=" "$retcode" ignore rc
+                splitsep "=" "$status" ignore state
             else
                 checkisomd5 --verbose $livedev
                 rc=$?
+                state="inactive"
             fi
             if [ "$rc" == "1" ]; then
+                die "CD check failed!"
+                exit 1
+            fi
+            if [ "$state" = "failed" ]; then
                 die "CD check failed!"
                 exit 1
             fi
@@ -32,6 +39,7 @@ run_checkisomd5() {
 
 dev="$1"
 path="$2" # optional, could be empty
+kickstart="$(getarg ks= inst.ks=)"
 
 [ -e "/dev/root" ] && exit 1 # we already have a root device!
 
